### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by kavun** [hyldmo/spotify-organizer#8]
I get a `INVALID_CLIENT: Invalid redirect URI` error

**Comment by hyldmo** [comment]
Apologies! Should be fixed now. Unfortunately there's not many features yet. If you have any good ideas, feel free to submit them here :)

**Comment by kavun** [comment]
Thanks! Oh I have lots of ideas 😃really i've been hoping someone would build

- bulk delete (I have 1600+ playlists)
- sort by recently updated (I know this would require lots of API calls, but I'm willing to wait) .. goal here being I want to delete all my playlists that haven't been updated in >2 months
- bulk make public / make private switches for my 100+ personal playlists
